-- Migration: 010_rls_new_tables.sql
-- Description: Row Level Security policies for the new passenger tables
--   and existing notifications table.
--
-- Policy philosophy:
--   • The backend uses the service_role key, which bypasses RLS entirely.
--     These policies protect against direct Supabase client access using the anon key.
--   • Users can only read their own data.
--   • Writes (insert/update/delete) go exclusively through the backend service role.
--   • passenger_documents: no direct client SELECT — documents are served via
--     HMAC-signed backend URLs (consistent with how verification images were handled).

-- ─────────────────────────────────────────────────────────────────────────────
-- booking_passengers
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.booking_passengers ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can read own booking passengers" ON public.booking_passengers;
CREATE POLICY "Users can read own booking passengers"
  ON public.booking_passengers FOR SELECT
  USING (
    booking_id IN (
      SELECT id FROM public.bookings WHERE user_id = auth.uid()
    )
  );

-- No direct client writes — all mutations go through the backend service role.

-- ─────────────────────────────────────────────────────────────────────────────
-- passenger_documents
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.passenger_documents ENABLE ROW LEVEL SECURITY;

-- No direct client access. Documents are served exclusively through
-- HMAC-signed URLs generated by the backend.

-- ─────────────────────────────────────────────────────────────────────────────
-- notifications
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- Users can read their own notifications.
DROP POLICY IF EXISTS "Users can read own notifications" ON public.notifications;
CREATE POLICY "Users can read own notifications"
  ON public.notifications FOR SELECT
  USING (user_id = auth.uid());

-- Users can update the 'is_read' field on their own notifications only.
-- Backend enforces that only 'is_read' can be toggled (not type, title, etc.).
DROP POLICY IF EXISTS "Users can mark own notifications as read" ON public.notifications;
CREATE POLICY "Users can mark own notifications as read"
  ON public.notifications FOR UPDATE
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- No INSERT from client — notifications are created exclusively by the backend.
-- No DELETE from client — notifications are retained for audit purposes.
